enable_live_input = true
latency_ms = 2.0
capacity_seconds = 1.0
plugin_chain = [
  "target/release/libdelay_clap_plugin.so",
  "target/release/libreverb_test_plugin.so"
]
input_device = "default"
output_device = "default"

[delay]
active_preset = "epic"

left_delay_ms = 400.0
right_delay_ms = 530.0
feedback = 0.65
mix = 0.5

[delay.presets.epic]
left_delay_ms = 400.0
right_delay_ms = 530.0
feedback = 0.65
mix = 0.5

[delay.presets.slapback]
left_delay_ms = 120.0
right_delay_ms = 120.0
feedback = 0.15
mix = 0.4

[delay.presets.canyon]
left_delay_ms = 800.0
right_delay_ms = 950.0
feedback = 0.85
mix = 0.6

[reverb]
active_preset = ""

comb_lengths = [1557.0, 1617.0, 1491.0, 1422.0]
allpass_lengths = [225.0, 556.0]
comb_feedback = 0.84
comb_dampening = 0.2
allpass_feedback = 0.5
left_spread = 0
right_spread = 23
mix = 0.4
wet_scale = 0.15

[reverb.presets.hall]
mix = 0.7
wet_scale = 0.25
