active_global_preset = "epic"
master_volume = 1.0

sample_rate = 48000
enable_live_input = false
latency_ms = 2.0
capacity_seconds = 1.0
plugin_chain = [
  "target/release/libsynth_plugin.so",
  "target/release/libamp_clap_plugin.so",
  "target/release/libcab_clap_plugin.so",
  "target/release/libvibrato_clap_plugin.so",
  "target/release/libdelay_clap_plugin.so",
  "target/release/libreverb_test_plugin.so"
]
input_device = "default"
output_device = "default"

# ==============================================================================
# GLOBAL PRESETS
# ==============================================================================


[global_presets.epic.synth]
attack_ms = 5.0
release_ms = 15.0
volume = 0.15

[global_presets.epic.amp]
drive = 8.0
tone = 0.4
level = 0.3

[global_presets.epic.cab]
low_cut_hz = 80.0
high_cut_hz = 5500.0
resonance = 0.707

[global_presets.epic.vibrato]
rate_hz = 4.5
depth_ms = 0.2
mix = 1.0

[global_presets.epic.delay]
left_delay_ms = 400.0
right_delay_ms = 530.0
feedback = 0.65
mix = 0.5

[global_presets.epic.reverb]
comb_lengths = [1557.0, 1617.0, 1491.0, 1422.0]
allpass_lengths = [225.0, 556.0]
comb_feedback = 0.84
comb_dampening = 0.2
allpass_feedback = 0.5
left_spread = 0
right_spread = 23
mix = 0.4
wet_scale = 0.15
